// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyAiYZg4bottZKMWMIXr-yLuAN3_W_3sj9E',
    appId: '1:710673444887:web:237a93e42efc24011b6c52',
    messagingSenderId: '710673444887',
    projectId: 'dass-30de1',
    authDomain: 'dass-30de1.firebaseapp.com',
    storageBucket: 'dass-30de1.appspot.com',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyCTtOGUS5PRgovC6j1kgwXjCncz66odXps',
    appId: '1:710673444887:android:2ea395e2e87c768f1b6c52',
    messagingSenderId: '710673444887',
    projectId: 'dass-30de1',
    storageBucket: 'dass-30de1.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyCWQaZx1BLJaQb9ZtSwWGGZsgdmi-gqVp4',
    appId: '1:710673444887:ios:8b624d8974c1fa241b6c52',
    messagingSenderId: '710673444887',
    projectId: 'dass-30de1',
    storageBucket: 'dass-30de1.appspot.com',
    iosBundleId: 'com.example.mentalhealth',
  );
}
