// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyAJa1tutsyqe-gQ3WzGLMfLgvAtFNFOOHs',
    appId: '1:257057403780:web:115d8528f85aae00b163d1',
    messagingSenderId: '257057403780',
    projectId: 'dass-6dfd1',
    authDomain: 'dass-6dfd1.firebaseapp.com',
    storageBucket: 'dass-6dfd1.firebasestorage.app',
    measurementId: 'G-T3HJEV0MRB',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyCoa8U51SAnEshpPMaxAi0XV_FiXqk0qyQ',
    appId: '1:257057403780:android:3ee268cc0c420c2fb163d1',
    messagingSenderId: '257057403780',
    projectId: 'dass-6dfd1',
    storageBucket: 'dass-6dfd1.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyDXOQCg0GnKp8yBo6qwPUeY5wwQrC5sR20',
    appId: '1:257057403780:ios:2f1fb6f0358b6465b163d1',
    messagingSenderId: '257057403780',
    projectId: 'dass-6dfd1',
    storageBucket: 'dass-6dfd1.firebasestorage.app',
    iosBundleId: 'com.example.mentalhealth',
  );

}